ignore:
  resource_names:
    - AccessGrant
    - AccessGrantsInstance
    - AccessGrantsLocation
    - AccessPointForObjectLambda
    - Bucket
    - Job
    - MultiRegionAccessPoint
    - StorageLensGroup
  field_paths:
    - CreateAccessPointInput.Name
    - CreateAccessPointInput.Bucket
resources:
  AccessPoint:
    exceptions:
      errors:
        404:
          code: NoSuchAccessPoint