ignore:
  field_paths:
    - CreateAccessPointInput.FileSystemId
    - CreateFileSystemInput.CreationToken
    - CreateFileSystemInput.ProvisionedThroughputInMibps
    - UpdateFileSystemInput.ProvisionedThroughputInMibps
    - FileSystemDescription.ProvisionedThroughputInMibps
    - CreateMountTargetInput.SecurityGroups
    - CreateMountTargetInput.FileSystemId
    - CreateMountTargetInput.SubnetId
resources:
  AccessPoint:
    exceptions:
      errors:
        404:
          code: AccessPointNotFound
  MountTarget:
    exceptions:
      errors:
        404:
          code: MountTargetNotFound
