ignore:
  field_paths:
    - DescribeDBClustersInput.DBClusterIdentifier
    - CreateDBClusterInput.DBClusterIdentifier
    - ModifyDBClusterInput.DBClusterIdentifier
    - DeleteDBClusterInput.DBClusterIdentifier
    - CreateDBClusterInput.MasterUserPassword
    - ModifyDBClusterInput.MasterUserPassword
    - CreateDBClusterInput.VpcSecurityGroupIds
    - ModifyDBClusterInput.VpcSecurityGroupIds
    - DBCluster.PendingModifiedValues
    - DescribeDBInstancesInput.DBInstanceIndentifier
    - CreateDBInstanceInput.DBInstanceIdentifier
    - ModifyDBInstanceInput.DBInstanceIdentifier
    - DeleteDBInstanceInput.DBInstanceIdentifier
    - CreateDBInstanceInput.MasterUserPassword
    - ModifyDBInstanceInput.MasterUserPassword
    - CreateDBInstanceInput.VpcSecurityGroupIds
    - ModifyDBInstanceInput.VpcSecurityGroupIds
    - CreateDBInstanceInput.DBSecurityGroups
    - ModifyDBInstanceInput.DBSecurityGroups
    - ModifyDBInstanceInput.DBSubnetGroupName # this is immutable
    - CreateDBParameterGroupInput.DBParameterGroupName
    - DeleteDBParameterGroupInput.DBParameterGroupName
    - ModifyDBParameterGroupInput.DBParameterGroupName
    - DescribeDBParameterGroupsInput.DBParameterGroupName
    - CreateDBClusterParameterGroupInput.DBClusterParameterGroupName
    - DeleteDBClusterParameterGroupInput.DBClusterParameterGroupName
    - ModifyDBClusterParameterGroupInput.DBClusterParameterGroupName
    - DescribeDBClusterParameterGroupsInput.DBClusterParameterGroupName
    - DescribeGlobalClustersInput.GlobalClusterIdentifier
    - ModifyGlobalClusterInput.GlobalClusterIdentifier
    - CreateGlobalClusterInput.GlobalClusterIdentifier
    - DeleteGlobalClusterInput.GlobalClusterIdentifier
  resource_names:
    - CustomAvailabilityZone
    - CustomDBEngineVersion
    - DBClusterEndpoint
    - DBClusterSnapshot
    - DBInstanceReadReplica
    - DBProxy
    - DBProxyEndpoint
    - DBSecurityGroup
    - DBSnapshot
    - DBSubnetGroup
    - EventSubscription
    - OptionGroup
