operations:
  AddRoleToDBInstance:
    resource_name: DBInstanceRoleAssociation
    operation_type: Create
  RemoveRoleFromDBInstance:
    resource_name: DBInstanceRoleAssociation
    operation_type: Delete

resources:
  DBInstance:
    fields:
      AllowMajorVersionUpgrade:
        from:
          operation: ModifyDBInstance
          path: AllowMajorVersionUpgrade
      DBClusterIdentifier:
        is_read_only: true
        from:
          operation: DescribeDBInstances
          path: DBInstances.DBClusterIdentifier
  DBCluster:
    fields:
      AllowMajorVersionUpgrade:
        from:
          operation: ModifyDBCluster
          path: AllowMajorVersionUpgrade
  DBInstanceRoleAssociation:
    exceptions:
      errors:
        404:
          code: DBInstanceNotFound
ignore:
  field_paths:
    - DescribeDBClustersInput.DBClusterIdentifier
    - CreateDBClusterInput.DBClusterIdentifier
    - ModifyDBClusterInput.DBClusterIdentifier
    - DeleteDBClusterInput.DBClusterIdentifier
    - CreateDBClusterInput.MasterUserPassword
    - ModifyDBClusterInput.MasterUserPassword
    - CreateDBClusterInput.VpcSecurityGroupIds
    - ModifyDBClusterInput.VpcSecurityGroupIds
    - CreateDBClusterInput.EngineVersion
    - ModifyDBClusterInput.EngineVersion
    - DBCluster.PendingModifiedValues
    - DescribeDBInstancesInput.DBInstanceIndentifier
    - CreateDBInstanceInput.DBInstanceIdentifier
    - ModifyDBInstanceInput.DBInstanceIdentifier
    - DeleteDBInstanceInput.DBInstanceIdentifier
    - CreateDBInstanceInput.MasterUserPassword
    - ModifyDBInstanceInput.MasterUserPassword
    - CreateDBInstanceInput.VpcSecurityGroupIds
    - ModifyDBInstanceInput.VpcSecurityGroupIds
    - CreateDBInstanceInput.DBSecurityGroups
    - ModifyDBInstanceInput.DBSecurityGroups
    - ModifyDBInstanceInput.DBSubnetGroupName # this is immutable
    - CreateDBInstanceInput.EngineVersion
    - ModifyDBInstanceInput.EngineVersion
    - CreateDBParameterGroupInput.DBParameterGroupName
    - CreateDBParameterGroupInput.DBParameterGroupFamily
    - DeleteDBParameterGroupInput.DBParameterGroupName
    - ModifyDBParameterGroupInput.DBParameterGroupName
    - ModifyDBParameterGroupInput.DBParameterGroupFamily
    - DescribeDBParameterGroupsInput.DBParameterGroupName
    - CreateDBClusterParameterGroupInput.DBClusterParameterGroupName
    - CreateDBClusterParameterGroupInput.DBParameterGroupFamily
    - DeleteDBClusterParameterGroupInput.DBClusterParameterGroupName
    - ModifyDBClusterParameterGroupInput.DBClusterParameterGroupName
    - ModifyDBClusterParameterGroupInput.DBParameterGroupFamily
    - DescribeDBClusterParameterGroupsInput.DBClusterParameterGroupName
    - DescribeGlobalClustersInput.GlobalClusterIdentifier
    - ModifyGlobalClusterInput.GlobalClusterIdentifier
    - CreateGlobalClusterInput.GlobalClusterIdentifier
    - DeleteGlobalClusterInput.GlobalClusterIdentifier
    - AddRoleToDBInstanceInput.DBInstanceIdentifier
    - AddRoleToDBInstanceInput.RoleArn
    - RemoveRoleFromDBInstanceInput.DBInstanceIdentifier
    - RemoveRoleFromDBInstanceInput.RoleArn
    - CreateOptionGroupInput.OptionGroupName
  resource_names:
    - CustomAvailabilityZone
    - CustomDBEngineVersion
    - DBClusterEndpoint
    - DBClusterSnapshot
    - DBInstanceReadReplica
    - DBProxy
    - DBProxyEndpoint
    - DBSecurityGroup
    - DBSnapshot
    - DBSubnetGroup
    - EventSubscription
    - BlueGreenDeployment