id: provider
title: AWS Provider
titlePlural: AWS Providers
category: Provider
overviewShort: "A Provider configures an AWS 'provider', i.e. a connection to a particular AWS account using a particular AWS IAM role."
overview: |
 A Provider configures an AWS 'provider', i.e. a connection to a particular AWS account using a particular AWS IAM role.
readme: |
 ## AWS Provider

 The Crossplane AWS Provider Resource configures an AWS 'provider', i.e. a connection to a particular AWS account using a particular AWS IAM Role.

 Full documentation can be found in the Crossplane [API Reference docs](https://crossplane.io/docs/0.5/api/crossplaneio/stack-aws/aws-crossplane-io-v1alpha3.html#Provider).