ignore:
  resource_names:
    - AccessEntry
    - Cluster
    - EksAnywhereSubscription
    - FargateProfile
    - Nodegroup
    - PodIdentityAssociation
  shape_names:
    - Nodegroup
    - Cluster
    - FargateProfile
    - IdentityProviderConfig
  field_paths:
    - DescribeAddonInput.ClusterName
    - CreateAddonInput.ClusterName
    - UpdateAddonInput.ClusterName
    - DeleteAddonInput.ClusterName
    - DescribeAddonInput.ClientRequestToken
    - CreateAddonInput.ClientRequestToken
    - UpdateAddonInput.ClientRequestToken
    - DeleteAddonInput.ClientRequestToken
