ignore:
  resource_names:
    - AuditSuppression
    - Authorizer
    - BillingGroup
    - CertificateFromCsr
    - CertificateProvider
    - CustomMetric
    - Dimension
    - DomainConfiguration
    - DynamicThingGroup
    - FleetMetric
    - Job
    - JobTemplate
    - KeysAndCertificate
    - MitigationAction
    - OTAUpdate
    - Package
    - PackageVersion
    - PolicyVersion
    - ProvisioningClaim
    - ProvisioningTemplate
    - ProvisioningTemplateVersion
    - RoleAlias
    - ScheduledAudit
    - SecurityProfile
    - Stream
    - ThingGroup
    - ThingType
    - TopicRule
    - TopicRuleDestination
  field_paths:
    - CreatePolicyInput.PolicyName
    - CreatePolicyOutput.PolicyName
    - CreateThingInput.ThingName
    - CreateThingOutput.ThingName