ignore:
  field_paths:
    - DescribeCacheParameterGroupsInput.CacheParameterGroupName
    - CreateCacheParameterGroupInput.CacheParameterGroupName
    - ModifyCacheParameterGroupInput.CacheParameterGroupName
    - DeleteCacheParameterGroupInput.CacheParameterGroupName
  resource_names:
    - CacheCluster
    - CacheSecurityGroup
    - CacheSubnetGroup
    - GlobalReplicationGroup
    - ReplicationGroup
    - ServerlessCache
    - ServerlessCacheSnapshot
    - Snapshot
    - User
    - UserGroup
