# Human readable title of application.
title: Amazon Web Services (AWS) Crossplane Stack

overviewShort: The AWS Stack enables resource management with Amazon Web Services.
overview: |-
 The Amazon Web Services Crossplane Stack adds support for managing AWS resources in Kubernetes.

 Amazon Elastic Kubernetes Service (EKS), Amazon Relational Database Service (RDS), Amazon ElastiCache, and Amazon Simple Storage Service (Amazon S3) can be provisioned, updated, and deleted by this stack.

# Markdown description of this entry
readme: |
 This `stack-aws` repository is the implementation of a Crossplane infrastructure
 [stack](https://github.com/crossplaneio/crossplane/blob/master/design/design-doc-stacks.md) for
 [Amazon Web Services (AWS)](https://aws.amazon.com).
 The stack that is built from the source code in this repository can be installed into a Crossplane control plane and adds the following new functionality:

 * Custom Resource Definitions (CRDs) that model AWS infrastructure and services (e.g. [Amazon Relational Database Service (RDS)](https://aws.amazon.com/rds/), [EKS clusters](https://aws.amazon.com/eks/), etc.)
 * Controllers to provision these resources in AWS based on the users desired state captured in CRDs they create
 * Implementations of Crossplane's [portable resource abstractions](https://crossplane.io/docs/master/running-resources.html), enabling AWS resources to fulfill a user's general need for cloud services

# Version of project (optional)
# If omitted the version will be filled with the docker tag
# If set it must match the docker tag
version: v0.1.0

# Maintainer names and emails.
maintainers:
- name: Jared Watts
  email: jared@upbound.io

# Owner names and emails.
owners:
- name: Jared Watts
  email: jared@upbound.io

# Human readable company name
company: Crossplane

# Keywords that describe this application and help search indexing
keywords:
- "amazon"
- "aws"
- "infrastructure"

# Links to more information about the application (about page, source code, etc.)
website: "https://crossplane.io"
source: "https://github.com/crossplaneio/stack-aws"

# RBAC ClusterRoles will be generated permitting this stack to use all verbs on all
# resources in the groups listed below.
permissionScope: Cluster
dependsOn:
- crd: '*.cache.crossplane.io/v1alpha1'
- crd: '*.compute.crossplane.io/v1alpha1'
- crd: '*.database.crossplane.io/v1alpha1'
- crd: '*.core.crossplane.io/v1alpha1'
- crd: '*.storage.crossplane.io/v1alpha1'
- crd: '*.workload.crossplane.io/v1alpha1'

# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0
