ignore:
  resource_names:
    - AccountAttribute
    - CapacityReservationFleet
    - CarrierGateway
    - ClientVpnEndpoint
    - ClientVpnRoute
    - CoipPool
    - CustomerGateway
    - DefaultSubnet
    - DefaultVpc
    - EgressOnlyInternetGateway
    - Fleet
    - FpgaImage
    - Image
    - Instance
    - InstanceEventWindow
    - InstanceExportTask
    - InternetGateway
    - KeyPair
    - LocalGatewayRouteTableVpcAssociation
    - LocalGatewayRoute
    - ManagedPrefixList
    - NatGateway
    - NetworkAclEntry
    - NetworkAcl
    - NetworkInsightsPath
    - NetworkInterfacePermission
    - NetworkInterface
    - PlacementGroup
    - ReservedInstancesListing
    - RouteTable
    - ReplaceRootVolumeTask
    - RestoreImageTask
    - SecurityGroup
    - Snapshot
    - SpotDatafeedSubscription
    - Subnet
    - StoreImageTask
    - SubnetCidrReservation
    - TrafficMirrorFilterRule
    - TrafficMirrorFilter
    - TrafficMirrorSession
    - TrafficMirrorTarget
    - TransitGatewayConnectPeer
    - TransitGatewayConnect
    - TransitGatewayMulticastDomain
    - TransitGatewayPeeringAttachment
    - TransitGatewayPrefixListReference
    - VpcEndpointConnectionNotification
    - Vpc
    - VpcCidrBlock
    - VpnConnectionRoute
    - VpnConnection
    - VpnGateway
    - Ipam
    - IpamScope
    - IpamPool
    - NetworkInsightsAccessScope
    - PublicIpv4Pool
    - CoipCidr
    - LocalGatewayRouteTable
    - LocalGatewayRouteTableVirtualInterfaceGroupAssociation
    - TransitGatewayPolicyTable
    - TransitGatewayRouteTableAnnouncement
    - VerifiedAccessEndpoint
    - VerifiedAccessGroup
    - VerifiedAccessInstance
    - VerifiedAccessTrustProvider
  shape_names:
    - Instance
    - SecurityGroupRule
  field_paths:
    - CreateVpcPeeringConnectionInput.DryRun
    - DeleteVpcPeeringConnectionInput.DryRun
    - RejectVpcPeeringConnectionInput.DryRun
    - AcceptVpcPeeringConnectionInput.DryRun
    - CreateVpcPeeringConnectionInput.VpcId
    - DeleteVpcPeeringConnectionInput.VpcId
    - RejectVpcPeeringConnectionInput.VpcId
    - AcceptVpcPeeringConnectionInput.VpcId
    - CreateVpcPeeringConnectionInput.PeerVpcId
    - DeleteVpcPeeringConnectionInput.PeerVpcId
    - RejectVpcPeeringConnectionInput.PeerVpcId
    - AcceptVpcPeeringConnectionInput.PeerVpcId
    - CreateVolumeInput.DryRun
    - CreateVolumeInput.KmsKeyId
    - CreateTransitGatewayInput.DryRun
    - DeleteTransitGatewayInput.DryRun
    - DescribeTransitGatewaysInput.DryRun
    - CreateTransitGatewayVpcAttachmentInput.DryRun
    - DeleteTransitGatewayVpcAttachmentInput.DryRun
    - DescribeTransitGatewayVpcAttachmentsInput.DryRun
    - RejectTransitGatewayVpcAttachmentInput.DryRun
    - AcceptTransitGatewayVpcAttachmentInput.DryRun
    - ModifyTransitGatewayVpcAttachmentInput.DryRun
    - CreateTransitGatewayVpcAttachmentInput.VpcId
    - CreateTransitGatewayVpcAttachmentInput.SubnetIds
    - CreateTransitGatewayVpcAttachmentInput.TransitGatewayId
    - ModifyTransitGatewayOptions.PropagationDefaultRouteTableId
    - ModifyTransitGatewayOptions.AssociationDefaultRouteTableId
    - ModifyTransitGatewayOptions.AddTransitGatewayCidrBlocks
    - ModifyTransitGatewayOptions.RemoveTransitGatewayCidrBlocks
    - CreateRouteInput.DryRun
    - CreateRouteInput.NatGatewayId
    - CreateRouteInput.TransitGatewayId
    - CreateRouteInput.VpcPeeringConnectionId
    - CreateRouteInput.RouteTableId
    - CreateRouteInput.InstanceId
    - CreateRouteInput.GatewayId
    - CreateVpcEndpointInput.VpcId
    - ModifyVpcEndpointInput.VpcId
    - CreateVpcEndpointInput.SubnetIds
    - CreateVpcEndpointInput.SecurityGroupIds
    - CreateVpcEndpointInput.DryRun
    - CreateVpcEndpointInput.RouteTableIds
    - Subnet.AvailableIpAddressCount
    - CreateLaunchTemplateVersionInput.LaunchTemplateId
    - CreateLaunchTemplateVersionInput.LaunchTemplateName
    - CreateLaunchTemplateVersionInput.DryRun
    - CreateLaunchTemplateVersionInput.ClientToken
    - CreateLaunchTemplateInput.DryRun
    - CreateLaunchTemplateInput.ClientToken
    - CreateTransitGatewayRouteInput.DryRun
    - CreateTransitGatewayRouteInput.TransitGatewayAttachmentId
    - CreateTransitGatewayRouteInput.TransitGatewayRouteTableId
    - CreateTransitGatewayRouteTableInput.DryRun
    - CreateTransitGatewayRouteTableInput.TransitGatewayId
    - CreateVpcEndpointServiceConfigurationInput.DryRun
    - CreateVpcEndpointServiceConfigurationInput.ClientToken
    - CreateVpcEndpointServiceConfigurationInput.GatewayLoadBalancerArns
    - CreateVpcEndpointServiceConfigurationInput.NetworkLoadBalancerArns
    - CreateVolumeInput.ClientToken
    - CreateVpcEndpointInput.ClientToken
    - CreateVpcEndpointOutput.ClientToken
    - CreateFlowLogsInput.ResourceIds
    - CreateFlowLogsInput.ResourceType
    - CreateFlowLogsInput.TagSpecifications
    - CreateFlowLogsInput.DeliverLogsPermissionArn
    - DescribeFlowLogsInput.FlowLogIds
    - DescribeFlowLogsInput.DryRun
    - CreateFlowLogsOutput.FlowLogIds
    - CreateFlowLogsOutput.Unsuccessful
    - CreateFlowLogsInput.DryRun
    - DeleteFlowLogsInput.FlowLogIds
    - DeleteFlowLogsInput.DryRun
    - CreateCapacityReservationInput.DryRun
    - CreateCapacityReservationInput.ClientToken
    - DescribeCapacityReservationsInput.DryRun
    - DescribeCapacityReservationsInput.ClientToken
    - ModifyCapacityReservationInput.DryRun
    - ModifyCapacityReservationInput.ClientToken
resources:
  Volume:
    exceptions:
      errors:
        404:
          code: InvalidVolume.NotFound
  LaunchTemplate:
    exceptions:
      errors:
        404:
          code: InvalidLaunchTemplateName.NotFoundException
  LaunchTemplateVersion:
    exceptions:
      errors:
        404:
          code: InvalidLaunchTemplateName.NotFoundException
  TransitGatewayRouteTable:
    exceptions:
      errors:
        404:
          code: InvalidRouteTableID.NotFound
  TransitGatewayRoute:
    exceptions:
      errors:
        404:
          code: InvalidRoute.NotFound
  FlowLog:
    fields:
      FlowLogId:
        is_read_only: true
        from:
          operation: DescribeFlowLogs
          path: FlowLogs.FlowLogId
      FlowLogStatus:
        is_read_only: true
        from:
          operation: DescribeFlowLogs
          path: FlowLogs.FlowLogStatus
      DeliverLogsStatus:
        is_read_only: true
        from:
          operation: DescribeFlowLogs
          path: FlowLogs.DeliverLogsStatus
      CreationTime:
        is_read_only: true
        from:
          operation: DescribeFlowLogs
          path: FlowLogs.CreationTime
      ResourceId:
        is_read_only: true
        from:
          operation: DescribeFlowLogs
          path: FlowLogs.ResourceId
      Tags:
        is_read_only: true
        from:
          operation: DescribeFlowLogs
          path: FlowLogs.Tags
operations:
  CreateFlowLogs:
    operation_type:
    - Create
    resource_name: FlowLog